// source: powertrade/powerusage/v1alpha/healthcheck.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_api_field_behavior_pb = require('../../../google/api/field_behavior_pb.js');
goog.object.extend(proto, google_api_field_behavior_pb);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.HealthCheckRequest', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.HealthCheckResponse', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.LivenessRequest', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.LivenessResponse', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.ReadinessRequest', null, global);
goog.exportSymbol('proto.powertrade.powerusage.v1alpha.ReadinessResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.HealthCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.HealthCheckRequest.displayName = 'proto.powertrade.powerusage.v1alpha.HealthCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.HealthCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.HealthCheckResponse.displayName = 'proto.powertrade.powerusage.v1alpha.HealthCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.LivenessRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.LivenessRequest.displayName = 'proto.powertrade.powerusage.v1alpha.LivenessRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.LivenessResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.LivenessResponse.displayName = 'proto.powertrade.powerusage.v1alpha.LivenessResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.ReadinessRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.ReadinessRequest.displayName = 'proto.powertrade.powerusage.v1alpha.ReadinessRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.powertrade.powerusage.v1alpha.ReadinessResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powertrade.powerusage.v1alpha.ReadinessResponse.displayName = 'proto.powertrade.powerusage.v1alpha.ReadinessResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.HealthCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    service: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.HealthCheckRequest;
  return proto.powertrade.powerusage.v1alpha.HealthCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.HealthCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string service = 1;
 * @return {string}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest} returns this
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.setService = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckRequest} returns this
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.clearService = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckRequest.prototype.hasService = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.HealthCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.HealthCheckResponse;
  return proto.powertrade.powerusage.v1alpha.HealthCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.HealthCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus = {
  SERVING_STATUS_UNSPECIFIED: 0,
  SERVING_STATUS_SERVING: 1,
  SERVING_STATUS_NOT_SERVING: 2
};

/**
 * optional ServingStatus status = 1;
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus}
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.prototype.getStatus = function() {
  return /** @type {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse.ServingStatus} value
 * @return {!proto.powertrade.powerusage.v1alpha.HealthCheckResponse} returns this
 */
proto.powertrade.powerusage.v1alpha.HealthCheckResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.LivenessRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    healthCheckRequest: (f = msg.getHealthCheckRequest()) && proto.powertrade.powerusage.v1alpha.HealthCheckRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessRequest}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.LivenessRequest;
  return proto.powertrade.powerusage.v1alpha.LivenessRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessRequest}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.powertrade.powerusage.v1alpha.HealthCheckRequest;
      reader.readMessage(value,proto.powertrade.powerusage.v1alpha.HealthCheckRequest.deserializeBinaryFromReader);
      msg.setHealthCheckRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.LivenessRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHealthCheckRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.powertrade.powerusage.v1alpha.HealthCheckRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional HealthCheckRequest health_check_request = 1;
 * @return {?proto.powertrade.powerusage.v1alpha.HealthCheckRequest}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.getHealthCheckRequest = function() {
  return /** @type{?proto.powertrade.powerusage.v1alpha.HealthCheckRequest} */ (
    jspb.Message.getWrapperField(this, proto.powertrade.powerusage.v1alpha.HealthCheckRequest, 1));
};


/**
 * @param {?proto.powertrade.powerusage.v1alpha.HealthCheckRequest|undefined} value
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessRequest} returns this
*/
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.setHealthCheckRequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessRequest} returns this
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.clearHealthCheckRequest = function() {
  return this.setHealthCheckRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.powertrade.powerusage.v1alpha.LivenessRequest.prototype.hasHealthCheckRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.LivenessResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    healthCheckResponse: (f = msg.getHealthCheckResponse()) && proto.powertrade.powerusage.v1alpha.HealthCheckResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessResponse}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.LivenessResponse;
  return proto.powertrade.powerusage.v1alpha.LivenessResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessResponse}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.powertrade.powerusage.v1alpha.HealthCheckResponse;
      reader.readMessage(value,proto.powertrade.powerusage.v1alpha.HealthCheckResponse.deserializeBinaryFromReader);
      msg.setHealthCheckResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.LivenessResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.LivenessResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHealthCheckResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.powertrade.powerusage.v1alpha.HealthCheckResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional HealthCheckResponse health_check_response = 1;
 * @return {?proto.powertrade.powerusage.v1alpha.HealthCheckResponse}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.getHealthCheckResponse = function() {
  return /** @type{?proto.powertrade.powerusage.v1alpha.HealthCheckResponse} */ (
    jspb.Message.getWrapperField(this, proto.powertrade.powerusage.v1alpha.HealthCheckResponse, 1));
};


/**
 * @param {?proto.powertrade.powerusage.v1alpha.HealthCheckResponse|undefined} value
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessResponse} returns this
*/
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.setHealthCheckResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.powertrade.powerusage.v1alpha.LivenessResponse} returns this
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.clearHealthCheckResponse = function() {
  return this.setHealthCheckResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.powertrade.powerusage.v1alpha.LivenessResponse.prototype.hasHealthCheckResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.ReadinessRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    healthCheckRequest: (f = msg.getHealthCheckRequest()) && proto.powertrade.powerusage.v1alpha.HealthCheckRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessRequest}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.ReadinessRequest;
  return proto.powertrade.powerusage.v1alpha.ReadinessRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessRequest}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.powertrade.powerusage.v1alpha.HealthCheckRequest;
      reader.readMessage(value,proto.powertrade.powerusage.v1alpha.HealthCheckRequest.deserializeBinaryFromReader);
      msg.setHealthCheckRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.ReadinessRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHealthCheckRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.powertrade.powerusage.v1alpha.HealthCheckRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional HealthCheckRequest health_check_request = 1;
 * @return {?proto.powertrade.powerusage.v1alpha.HealthCheckRequest}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.getHealthCheckRequest = function() {
  return /** @type{?proto.powertrade.powerusage.v1alpha.HealthCheckRequest} */ (
    jspb.Message.getWrapperField(this, proto.powertrade.powerusage.v1alpha.HealthCheckRequest, 1));
};


/**
 * @param {?proto.powertrade.powerusage.v1alpha.HealthCheckRequest|undefined} value
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessRequest} returns this
*/
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.setHealthCheckRequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessRequest} returns this
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.clearHealthCheckRequest = function() {
  return this.setHealthCheckRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.powertrade.powerusage.v1alpha.ReadinessRequest.prototype.hasHealthCheckRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.powertrade.powerusage.v1alpha.ReadinessResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    healthCheckResponse: (f = msg.getHealthCheckResponse()) && proto.powertrade.powerusage.v1alpha.HealthCheckResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessResponse}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powertrade.powerusage.v1alpha.ReadinessResponse;
  return proto.powertrade.powerusage.v1alpha.ReadinessResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessResponse}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.powertrade.powerusage.v1alpha.HealthCheckResponse;
      reader.readMessage(value,proto.powertrade.powerusage.v1alpha.HealthCheckResponse.deserializeBinaryFromReader);
      msg.setHealthCheckResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powertrade.powerusage.v1alpha.ReadinessResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powertrade.powerusage.v1alpha.ReadinessResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHealthCheckResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.powertrade.powerusage.v1alpha.HealthCheckResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional HealthCheckResponse health_check_response = 1;
 * @return {?proto.powertrade.powerusage.v1alpha.HealthCheckResponse}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.getHealthCheckResponse = function() {
  return /** @type{?proto.powertrade.powerusage.v1alpha.HealthCheckResponse} */ (
    jspb.Message.getWrapperField(this, proto.powertrade.powerusage.v1alpha.HealthCheckResponse, 1));
};


/**
 * @param {?proto.powertrade.powerusage.v1alpha.HealthCheckResponse|undefined} value
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessResponse} returns this
*/
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.setHealthCheckResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.powertrade.powerusage.v1alpha.ReadinessResponse} returns this
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.clearHealthCheckResponse = function() {
  return this.setHealthCheckResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.powertrade.powerusage.v1alpha.ReadinessResponse.prototype.hasHealthCheckResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.powertrade.powerusage.v1alpha);
