name: 'Deploy and Run Cypress'
on: [pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy front-end'
    outputs:
      VERCEL_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: 'Deploy to Vercel'
        # run: |
        #   npx vercel --token ${VERCEL_TOKEN}
        # env:
        #   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        #   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        #   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
      - name: Get Deployment URL
        run: |
          echo "${{ steps.deploy-vercel-staging.outputs.preview-url }}"
        env:
          VERCEL_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
  chrome-and-firefox-e2e:
    name: E2E on Chrome and Firefox
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      # Run the E2E tests against the new Vercel deployment
      - name: Run E2E tests (Cypress) with Chrome
        uses: cypress-io/github-action@v2 # See https://github.com/cypress-io/github-action
        with:
          wait-on: ${{ needs.vercel.outputs.VERCEL_URL }} # Be sure that the endpoint is ready by pinging it before starting tests, it has a timeout of 60seconds
          config: baseUrl=${{ needs.vercel.outputs.VERCEL_URL }} # Overriding baseUrl provided by config file to test the new deployment
          browser: chrome
      - name: Run E2E tests (Cypress) with FireFox
        uses: cypress-io/github-action@v2 # See https://github.com/cypress-io/github-action
        with:
          wait-on: ${{ needs.vercel.outputs.VERCEL_URL }} # Be sure that the endpoint is ready by pinging it before starting tests, it has a timeout of 60seconds
          config: baseUrl=${{ needs.vercel.outputs.VERCEL_URL }} # Overriding baseUrl provided by config file to test the new deployment
          browser: firefox
  edge-e2e:
    name: E2E on Edge
    runs-on: windows-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - name: Run E2E tests (Cypress)
        uses: cypress-io/github-action@v2 # See https://github.com/cypress-io/github-action
        with:
          wait-on: ${{ needs.vercel.outputs.VERCEL_URL }} # Be sure that the endpoint is ready by pinging it before starting tests, it has a timeout of 60seconds
          config: baseUrl=${{ needs.vercel.outputs.VERCEL_URL }} # Overriding baseUrl provided by config file to test the new deployment
          browser: edge
