name: 'Deploy and Run Cypress'
on: [pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy front-end'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: 'Deploy to Vercel'
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  chrome-e2e:
    name: E2E on Chrome
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ github.event.deployment_status.target_url }}
          browser: chrome
  edge-e2e:
    name: E2E on Edge
    runs-on: windows-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ github.event.deployment_status.target_url }}
          browser: edge
  firefox-e2e:
    name: E2E on Firefox
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ github.event.deployment_status.target_url }}
          browser: firefox
