name: 'Deploy and Run Cypress'
on: [pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy front-end'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: 'Deploy to Vercel'
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  chrome-e2e:
    name: E2E on Chrome
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          wait-on: ${{ env.VERCEL_DEPLOYMENT_URL }}
          config: baseUrl=${{ env.VERCEL_DEPLOYMENT_URL }}
          browser: chrome
        env:
          # Enables Cypress debugging logs, very useful if Cypress crashes, like out-of-memory issues.
          #          DEBUG: "cypress:*" # Enable all logs. See https://docs.cypress.io/guides/references/troubleshooting.html#Print-DEBUG-logs
          DEBUG: 'cypress:server:util:process_profiler' # Enable logs for "memory and CPU usage". See https://docs.cypress.io/guides/references/troubleshooting.html#Log-memory-and-CPU-usage
  edge-e2e:
    name: E2E on Edge
    runs-on: windows-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          wait-on: ${{ env.VERCEL_DEPLOYMENT_URL }}
          config: baseUrl=${{ env.VERCEL_DEPLOYMENT_URL }}
          browser: edge
  firefox-e2e:
    name: E2E on Firefox
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          wait-on: ${{ env.VERCEL_DEPLOYMENT_URL }}
          config: baseUrl=${{ env.VERCEL_DEPLOYMENT_URL }}
          browser: firefox
