name: E2E on Firefox
on: push
jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm run dev
          wait-on: http://localhost:3000
